// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANZi4edjWGcXiCqIXoLoEpsS0u-1VgJLo',
    appId: '1:437480202480:web:27f6fc56243ae768e16235',
    messagingSenderId: '437480202480',
    projectId: 'diplom-a4d02',
    authDomain: 'diplom-a4d02.firebaseapp.com',
    storageBucket: 'diplom-a4d02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC11dd7u4-i_KmDPKefUd0cmOJDibVP2Og',
    appId: '1:437480202480:android:f3dd288f4dc6f9bae16235',
    messagingSenderId: '437480202480',
    projectId: 'diplom-a4d02',
    storageBucket: 'diplom-a4d02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK7JPxzuKnI0FSDNLb2ZQEr9OSFI3AZaw',
    appId: '1:437480202480:ios:8deb08d85e067fa4e16235',
    messagingSenderId: '437480202480',
    projectId: 'diplom-a4d02',
    storageBucket: 'diplom-a4d02.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK7JPxzuKnI0FSDNLb2ZQEr9OSFI3AZaw',
    appId: '1:437480202480:ios:8deb08d85e067fa4e16235',
    messagingSenderId: '437480202480',
    projectId: 'diplom-a4d02',
    storageBucket: 'diplom-a4d02.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANZi4edjWGcXiCqIXoLoEpsS0u-1VgJLo',
    appId: '1:437480202480:web:293369833b7f02cbe16235',
    messagingSenderId: '437480202480',
    projectId: 'diplom-a4d02',
    authDomain: 'diplom-a4d02.firebaseapp.com',
    storageBucket: 'diplom-a4d02.firebasestorage.app',
  );
}
